In [1]:
import torch

In [20]:
x = torch.empty(1)
print("empty(1):",x)

empty(1): tensor([1.4013e-45])


In [26]:
x = torch.empty(3)
print("empty(3):",x)

empty(3): tensor([9.2196e-41, 1.8980e+01, 2.6757e-29])


In [27]:
x = torch.empty(2, 3)
print("empty(2, 3):",x)

empty(2, 3): tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 4.5829e-41,  0.0000e+00, -3.6893e+19]])


In [28]:
x = torch.empty(2, 2, 3)
print("empty(2, 2, 3):",x)

empty(2, 2, 3): tensor([[[ 0.0000e+00, -3.6893e+19,  0.0000e+00],
         [-3.6893e+19,  1.1210e-44,  3.6893e+19]],

        [[ 6.9429e-29,  3.6902e+19,  0.0000e+00],
         [-3.6893e+19,  0.0000e+00, -3.6893e+19]]])


In [30]:
x = torch.empty(2, 2, 2, 3)
print("empty(2, 2, 2, 3):",x)

empty(2, 2, 2, 3): tensor([[[[ 0.0000e+00, -3.6893e+19,  6.9874e-29],
          [-8.5920e+09,  4.2007e-29,  4.5829e-41]],

         [[ 4.2144e-29,  4.5829e-41,  4.2109e-29],
          [ 4.5829e-41,  4.2070e-29,  4.5829e-41]]],


        [[[ 4.2072e-29,  4.5829e-41,  4.2105e-29],
          [ 4.5829e-41,  4.2039e-29,  4.5829e-41]],

         [[ 3.5322e-29,  4.5829e-41,  3.0783e-29],
          [ 4.5829e-41,  4.2099e-29,  4.5829e-41]]]])


In [31]:
x = torch.zeros(5, 3)
print("zeros(5, 3):", x)

zeros(5, 3): tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [32]:
x = torch.rand(5, 3)
print("rand(5, 3):", x)

rand(5, 3): tensor([[0.1301, 0.6897, 0.5328],
        [0.6313, 0.1902, 0.0924],
        [0.6566, 0.7913, 0.6699],
        [0.4572, 0.7586, 0.5778],
        [0.2553, 0.2757, 0.7374]])


In [33]:
x = torch.ones(3,4)
print("ones(3, 4):", x)

ones(3, 4): tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [34]:
print("size", x.size())
print("shape", x.shape)

size torch.Size([3, 4])
shape torch.Size([3, 4])


In [38]:
print(x.dtype)
x = torch.zeros(5, 3, dtype = torch.float16)
print(x)
print(x.dtype)

torch.float16
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [39]:
x = torch.tensor([5.5, 3])
print(x, x.dtype)

tensor([5.5000, 3.0000]) torch.float32


In [41]:
x = torch.tensor([5.5, 3], requires_grad = True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [50]:
x = torch.ones(2, 2)
y = torch.rand(2, 2)
z = x / y
print(x)
print(y)
print(z)
# torch.mul(x,y)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4841, 0.4679],
        [0.0311, 0.3426]])
tensor([[ 2.0657,  2.1371],
        [32.1214,  2.9191]])


In [56]:
x = torch.rand(5, 3)
print(x)
print("x[:, 0]", x[:, 0])
print("x[1, :]", x[1, :])
print("x[:, 1]", x[1, 1])

print("x[1, 1].item()", x[1, 1].item())

tensor([[0.2118, 0.4466, 0.1453],
        [0.1475, 0.4153, 0.6217],
        [0.9642, 0.5282, 0.0384],
        [0.0841, 0.3004, 0.6296],
        [0.9864, 0.3357, 0.1829]])
x[:, 0] tensor([0.2118, 0.1475, 0.9642, 0.0841, 0.9864])
x[1, :] tensor([0.1475, 0.4153, 0.6217])
x[:, 1] tensor(0.4153)
x[1, 1].item() 0.4153144955635071


In [63]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1, 8)
print(z)
print(x.size(), y.size(), z.size())

tensor([[0.5607, 0.1174, 0.5771, 0.5678],
        [0.4408, 0.0157, 0.3130, 0.0294],
        [0.7944, 0.1587, 0.4438, 0.0650],
        [0.8959, 0.5556, 0.0143, 0.1880]])
tensor([0.5607, 0.1174, 0.5771, 0.5678, 0.4408, 0.0157, 0.3130, 0.0294, 0.7944,
        0.1587, 0.4438, 0.0650, 0.8959, 0.5556, 0.0143, 0.1880])
tensor([[0.5607, 0.1174, 0.5771, 0.5678, 0.4408, 0.0157, 0.3130, 0.0294],
        [0.7944, 0.1587, 0.4438, 0.0650, 0.8959, 0.5556, 0.0143, 0.1880]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [69]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [72]:
a.add_(1)
print(a)
print(b)

tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


In [74]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
c = torch.tensor(a)
print(a)
print(b)
print(c)
a+= 1
print(a)
print(b)
print(c)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [77]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.rand(2, 2).to(device)

In [79]:
# AUTOGRAD
x = torch.rand(3, requires_grad=True)
y = x + 2
print(x)
print(y)
print(y.grad_fn)

tensor([0.3627, 0.3592, 0.9919], requires_grad=True)
tensor([2.3627, 2.3592, 2.9919], grad_fn=<AddBackward0>)


In [81]:
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([16.7466, 16.6979, 26.8538], grad_fn=<MulBackward0>)
tensor(20.0994, grad_fn=<MeanBackward0>)


In [93]:
# z.backward()
print(x.grad)

tensor([4.7253, 4.7185, 5.9837])


In [98]:
a = torch.randn(2, 2)
b = (a * a).sum()
print(a)
print(b)
print(a.requires_grad)
print(b.grad_fn)

a.requires_grad_(True)
b = (a * a).sum()
print(a.requires_grad)
print(b.grad_fn)

tensor([[ 0.1881,  0.7609],
        [-1.0803, -0.1346]])
tensor(1.7995)
False
None
True


In [102]:
a = torch.rand(2, 2, requires_grad=True)
b = a. detach()
print(a)
print(b)
print(a.requires_grad)
print(b.requires_grad)

tensor([[0.8411, 0.8493],
        [0.5399, 0.7518]], requires_grad=True)
tensor([[0.8411, 0.8493],
        [0.5399, 0.7518]])
True
False


In [106]:
a = torch.randn(2, 2, requires_grad = True)
print(a.requires_grad)
with torch.no_grad():
    b = a ** 2
    print(b.requires_grad)
    print(a)
    print(b)


True
False
tensor([[ 0.4613, -0.2056],
        [-0.6854,  0.2685]], requires_grad=True)
tensor([[0.2128, 0.0423],
        [0.4698, 0.0721]])


In [169]:
# LINEAR REGRESSION
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8], dtype = torch.float32)
y = torch.tensor([2, 4, 6, 8, 10, 12, 14, 16], dtype = torch.float32)
w = torch.tensor(0.0, dtype = torch.float32, requires_grad = True)

def forward(x):
    return w * x 

def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

x_test = 5.0
print(f"Prediction before training: f({x_test}) = {forward(x_test).item():.3f}")

# Training
learning_rate = 0.01
n_epochs = 100

# Prediction
for epoch in range(n_epochs):
    y_pred = forward(x)

# Loss
l = loss(y, y_pred)

# Calculate gradient = backward pass
l.backward()

# Update weights
# w.data = w.data - learning_rate * w.grad
with torch.no_grad():
    w -= learning_rate * w.grad

# zero the gradient after updating
w.grad.zero_()

if (epoch + 1) % 10 == 0:
    print(f"epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.3f}")
    
print(f"Prediction after training: f({x_test}) = {forward(x_test).item():.3f}")  




Prediction before training: f(5.0) = 0.000
epoch 100: w = 1.020, loss = 102.000
Prediction after training: f(5.0) = 5.100
